version: '3.6'
services:
  server:
    image: ${REGISTRY:-}${IMAGE_NAME:?err}
    build:
      context: ../
    environment:
      TZ: HST
    ports:
      - 8080:80
    deploy:
      labels:
        # configures the reverse proxy
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.servicePath: "/boilerplate/${BUILD_VERSION:?err}/"
        com.df.reqPathSearch: "/boilerplate/${BUILD_VERSION:?err}/"
        com.df.reqPathReplace: "/"
        com.df.port: "8080"
        # allows Jenkins to kill this stack after the related branch has been deleted
        edu.hawaii.clean-orphaned: "true"
        edu.hawaii.repo: "git@github.com:UniversityOfHawaii/uh-its-boilerplate.git"
        edu.hawaii.branch: ${BUILD_VERSION:?err}
