##
# The following environment variables will be set by Jenkins for THE TEST swarm:
#   BUILD_VERSION = releaseDataFromGit.versionFromGitStatus()
#   REGISTRY = releaseDataFromGit.registryFromGitStatus()
##
version: '3.6'
services:
  server:
    image: ${REGISTRY?:err}uh-its-boilerplate:${BUILD_VERSION?:err}
    build:
      context: ../
    environment:
      TZ: HST
    ports:
      - "80"
    deploy:
      labels:
        # configures the traefik reverse proxy
        traefik.enable: "true"
        traefik.http.routers.boilerplate-${BUILD_VERSION:?err}-router.rule: "PathPrefix(`/boilerplate/${BUILD_VERSION:?err}`)"
        traefik.http.routers.boilerplate-${BUILD_VERSION:?err}-router.middlewares: "boilerplate-${BUILD_VERSION:?err}-middleware1"
        traefik.http.middlewares.boilerplate-${BUILD_VERSION:?err}-middleware1.stripprefix.prefixes: "/boilerplate/${BUILD_VERSION:?err}"
        traefik.http.routers.boilerplate-${BUILD_VERSION:?err}-router.service: "boilerplate-${BUILD_VERSION:?err}-service"
        traefik.http.services.boilerplate-${BUILD_VERSION:?err}-service.loadbalancer.server.port: "80" 
        # allows Jenkins to kill this stack after the related branch has been deleted
        edu.hawaii.clean-orphaned: "true"
        edu.hawaii.repo: "git@github.com:UniversityOfHawaii/uh-its-boilerplate.git"
        edu.hawaii.branch: ${BUILD_VERSION:?err}
    networks:
      - proxy
      - default
networks:
  proxy:
    external: true
  default:
    attachable: true
